INSERT INTO "School" (id, name, code, ward, lga, address, "isActive", "createdAt", "updatedAt")
VALUES
(gen_random_uuid(), 'Ahmadu Coomassie Model Primary School', '1212110014', 'GABAS I', 'Katsina LGA', 'GABAS I, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Dikko Memorial Primary School', '1212110021', 'GABAS I', 'Katsina LGA', 'GABAS I, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Dr Ibrahim Shehu Shema Primary School', '1212110006', 'GABAS I', 'Katsina LGA', 'GABAS I, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Fatima Ibrahim Shema Primary School', '1212110042', 'GABAS I', 'Katsina LGA', 'GABAS I, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Gidado Primary School', '1212110034', 'GABAS I', 'Katsina LGA', 'GABAS I, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Hassan Usman Science Model Primary School', '1212110045', 'GABAS I', 'Katsina LGA', 'GABAS I, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Hassu Iro Inko Primary School', '1212140206', 'GABAS I', 'Katsina LGA', 'GABAS I, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Model Quranic Primary School', '1212110053', 'GABAS I', 'Katsina LGA', 'GABAS I, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Modoji Village Primary School', '1212110005', 'GABAS I', 'Katsina LGA', 'GABAS I, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Sandan Bale Quranic Model Primary School', '1212110004', 'GABAS I', 'Katsina LGA', 'GABAS I, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Dan Masani Bala Saulawa Primary School', '1212110031', 'GABAS II', 'Katsina LGA', 'GABAS II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Family Support Programme Primary School', '1212110142', 'GABAS II', 'Katsina LGA', 'GABAS II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Mamman Barda Memorial Primary School', '1212110024', 'GABAS II', 'Katsina LGA', 'GABAS II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Matawalle Ummaru Primary School', '1212110046', 'GABAS II', 'Katsina LGA', 'GABAS II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Talba Ibrahim Science Model Primary School', '1212110044', 'GABAS II', 'Katsina LGA', 'GABAS II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Sarkin Noma Bala Kamfani Primary School', '1212110037', 'YAMMA I', 'Katsina LGA', 'YAMMA I, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Comrade Muntari Lawal Primary School', '1212110018', 'YAMMA II', 'Katsina LGA', 'YAMMA II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Government School for the Blind Primary School', '1211410086', 'YAMMA II', 'Katsina LGA', 'YAMMA II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Hamza Maigoro Primary School', '1212110016', 'YAMMA II', 'Katsina LGA', 'YAMMA II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Hassan Rafin Dadi Primary School', '1212110002', 'YAMMA II', 'Katsina LGA', 'YAMMA II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Mannir Yakubu Primary School', '1212140208', 'YAMMA II', 'Katsina LGA', 'YAMMA II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Muhammadu Buhari Primary School Katsina', '1212110050', 'YAMMA II', 'Katsina LGA', 'YAMMA II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Dan-Marna Primary School', '1212110017', 'KUDU I', 'Katsina LGA', 'KUDU I, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Ummarun Dallaje Primary School', '1212110001', 'KUDU I', 'Katsina LGA', 'KUDU I, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Waziri Zayyana Primary School', '1212110035', 'KUDU I', 'Katsina LGA', 'KUDU I, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Isa Kaita Quranic Model Primary School', '1212110043', 'KUDU II', 'Katsina LGA', 'KUDU II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Jabiru Abdullahi Memorial Primary School', '1212110040', 'KUDU II', 'Katsina LGA', 'KUDU II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Muhammad Dodo Science Model Primary School', '1212110038', 'KUDU II', 'Katsina LGA', 'KUDU II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Sabuwar Unguwa New Extension Primary School', '1212110023', 'KUDU II', 'Katsina LGA', 'KUDU II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Bilingual School', '1212110051', 'KUDU III', 'Katsina LGA', 'KUDU III, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Dallatu Aminu Primary School', '1212110056', 'KUDU III', 'Katsina LGA', 'KUDU III, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Dr Kabir Usman Model Primary School', '1212110039', 'KUDU III', 'Katsina LGA', 'KUDU III, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Fatima Baika Girls Primary School', '1212110041', 'KUDU III', 'Katsina LGA', 'KUDU III, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Hon Sani Aliyu Danlami Primary School', '1212110012', 'KUDU III', 'Katsina LGA', 'KUDU III, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Senator Ibrahim Ida Primary School', '1212110009', 'KUDU III', 'Katsina LGA', 'KUDU III, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Musa Yar''adua Quranic Model Primary School', '1212110015', 'AREWA I', 'Katsina LGA', 'AREWA I, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Sir Usman Nagogo Memorial Nursery, Primary and the Deaf School (NA)', '1212110057', 'AREWA I', 'Katsina LGA', 'AREWA I, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Barau Tukur Mangal Primary School', '1212110007', 'AREWA II', 'Katsina LGA', 'AREWA II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Farin Yaro Primary School', '1212110036', 'AREWA II', 'Katsina LGA', 'AREWA II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Garba Kaita Memorial Primary School', '1212110019', 'AREWA II', 'Katsina LGA', 'AREWA II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Anas Mukaddas Nursery and Primary School', '1212110020', 'AREWA II', 'Katsina LGA', 'AREWA II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Gobarau Primary School', '1212110003', 'AREWA II', 'Katsina LGA', 'AREWA II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Iro Isansi Science Model Primary School', '1212110150', 'AREWA II', 'Katsina LGA', 'AREWA II, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Ambassador Audu Magaji Primary School', '1212140218', 'SHINKAFI A', 'Katsina LGA', 'SHINKAFI A, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Tafarki Dahiru Memorial (Dan-Nabaso) Primary School', '1212110029', 'SHINKAFI A', 'Katsina LGA', 'SHINKAFI A, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Dr. Abdulmuminu Kabir Usman (Shinkafi Quranic) Model Primary School', '1212110025', 'SHINKAFI A', 'Katsina LGA', 'SHINKAFI A, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Marai Nomadic Primary School', '1212110022', 'SHINKAFI A', 'Katsina LGA', 'SHINKAFI A, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Dr Kabir Magaji Gafiya Primary School', '1212110152', 'SHINKAFI B', 'Katsina LGA', 'SHINKAFI B, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Hayin Gagare Primary School', '1212140216', 'SHINKAFI B', 'Katsina LGA', 'SHINKAFI B, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Katoge Primary School', '1212140215', 'SHINKAFI B', 'Katsina LGA', 'SHINKAFI B, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Kadifawa Primary School', '1212110033', 'SHINKAFI B', 'Katsina LGA', 'SHINKAFI B, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Kambarawa Primary School', '1212110032', 'SHINKAFI B', 'Katsina LGA', 'SHINKAFI B, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Kaurar Rafa Primary School', '1212110028', 'SHINKAFI B', 'Katsina LGA', 'SHINKAFI B, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Sa''i Amadu Nafuntua (Kwado) Primary School', '1212110030', 'SHINKAFI B', 'Katsina LGA', 'SHINKAFI B, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Nadada Memorial (Makera) Primary School', '1212110026', 'SHINKAFI B', 'Katsina LGA', 'SHINKAFI B, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Sabon Garin Bakuru Primary School', '1212110027', 'SHINKAFI B', 'Katsina LGA', 'SHINKAFI B, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Lawal Ba Nomadic Primary School', '1212110010', 'KANGIWA', 'Katsina LGA', 'KANGIWA, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Liman Munir (Tsallatori) Primary School', '1212140205', 'KANGIWA', 'Katsina LGA', 'KANGIWA, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Liman Rufai (Kukar Gesa) Primary School', '1212140217', 'KANGIWA', 'Katsina LGA', 'KANGIWA, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Nagogo Science Model Primary School', '1212110008', 'KANGIWA', 'Katsina LGA', 'KANGIWA, Katsina LGA, Katsina State', true, now(), now()),
(gen_random_uuid(), 'Pilot Senior Nagogo Primary School', '1212110058', 'KANGIWA', 'Katsina LGA', 'KANGIWA, Katsina LGA, Katsina State', true, now(), now());
